ALTER TABLE tbltickets 
ADD COLUMN TicketNumber INT PRIMARY KEY AUTO_INCREMENT NOT NULL;
-- MODIFY COLUMN Problem VARCHAR(50) NOT NULL,
-- MODIFY COLUMN Details VARCHAR(80) NOT NULL,
-- MODIFY COLUMN Status VARCHAR(20) NOT NULL,
-- MODIFY COLUMN CreatedBy VARCHAR(50) NOT NULL,
-- MODIFY COLUMN DateCreated DATETIME NOT NULL,
-- MODIFY COLUMN AssignedTo VARCHAR(50) NULL,
-- MODIFY COLUMN DateAssigned DATETIME NULL,
-- MODIFY COLUMN DateCompleted DATETIME NULL,
-- MODIFY COLUMN ApprovedBy VARCHAR(50) NULL,
-- MODIFY COLUMN DateApproved DATETIME NULL;
